In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('data/final/12-US-House-poll-responses-clean.tsv', sep='\t', lineterminator='\n')

In [5]:
df.head()

,Democrat,Republican,Undecided,Other,Not Voting,poll_slug,survey_house,start_date,end_date,question_text,sample_subpopulation,observations,margin_of_error,mode,partisanship,partisan_affiliation
0,44.0,44.0,9.0,2.0,1.0,yougov-economist-16733,YouGov/Economist,2012-11-03,2012-11-05,NaN,Likely Voters,743.0,NaN,Internet,Nonpartisan,None
1,48.0,49.0,1.0,NaN,NaN,cnn-16606,CNN,2012-11-02,2012-11-04,NaN,Likely Voters,693.0,3.5,Live Phone,Nonpartisan,None
2,47.0,46.0,7.0,NaN,NaN,dailykos-seiu-ppp-d-16640,DailyKos/SEIU/PPP (D),2012-11-01,2012-11-04,NaN,Likely Voters,1300.0,2.7,Automated Phone,Sponsor,Dem
3,46.0,46.0,7.0,1.0,1.0,democracy-corps-d-16617,Democracy Corps (D),2012-11-01,2012-11-04,NaN,Likely Voters,1080.0,NaN,Live Phone,Pollster,Dem
4,46.0,46.0,5.0,3.0,NaN,rasmussen-16649,Rasmussen,2012-10-29,2012-11-04,NaN,Likely Voters,7000.0,NaN,Automated Phone,Nonpartisan,None

In [11]:
df_election_2012 = pd.read_excel('data/final/federalelections2012.xls', sheet_name=12)

In [12]:
df_election_2012.head()

,1,STATE ABBREVIATION,STATE,D,FEC ID#,(I),CANDIDATE NAME (First),CANDIDATE NAME (Last),CANDIDATE NAME,TOTAL VOTES,...,CONVENTION VOTES 2ND BALLOT,CONVENTION % 2ND BALLOT,CONVENTION VOTES 3RD BALLOT,CONVENTION % 3RD BALLOT,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,FOOTNOTES
0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3.0,CT,Connecticut,NaN,NaN,NaN,NaN,NaN,DISTRICT 1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.0,CT,Connecticut,01,H8CT01046,(I),John B.,Larson,"Larson, John B.",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,6.0,CT,Connecticut,01,H2CT01163,NaN,John Henry,Decker,"Decker, John Henry",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,7.0,CT,Connecticut,01,H2CT01155,NaN,Michael W.,McDonald,"McDonald, Michael W.",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
raising_2012 = pd.read_csv('data/final/weball12.txt', sep='|', lineterminator='\n')